language: node_js
node_js:
  - "node"
  - "6.11.2"
before_install:
  - npm install
script:
  - npm run test
after_script:
  - npm run coverage

env:
  CODECLIMATE_REPO_TOKEN: ab14f029319defa6d4d279712330e17b674d6be5d4960b33fbf3581064954dda
  global:
    - TESTapiKey=AIzaSyDkPt22XPPEkOkOYPh6ISF_uvvToJqh2Og
    - TESTauthDomain=post-it-test.firebaseapp.com
    - TESTdatabaseURL=https://post-it-test.firebaseio.com
    - TESTprojectId=post-it-test
    - TESTstorageBucket=post-it-test.appspot.com
    - TESTmessagingSenderId=653724014643

    - GMAIL_USERNAME=postitbydanny@gmail.com
    - PASS=andela098

    - NEXMO_API_KEY=d50a66e6
    - NEXTMO_API_SECRET=0848dec271458a5c
    
